### ISSUE TITLE
个人评论

### ISSUE THREAD

**Issue by yyl99311** [df7c5117/Guangzhou-Metro-Guidance-System-in-CSS#2]
这是个CSS库吧，这个Project真是充满创意啊，有了这个以后做有关的东西就不用贴图片了，省了不少空间。点个赞！
不过个人觉得广州地铁的车站编号真的是鸡肋，感觉没什么用处，乱糟糟的。
最后，高三这一年，加油吧！

**Comment by df7c5117** [comment]
+1，GZMTR的编号乱七八糟。
苟利高考生死以……
